#docker-compose.yml (Base)
version: '3.4'
services:
  recipe-api:
    restart: always
    image: quattro004/recipieces-recipe-api:${TAG:-latest}
    build:
      context: .
      dockerfile: RecipeApi/Dockerfile
    depends_on:
      - mongo

  web:
    restart: always
    image: quattro004/recipieces-web:${TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - recipe-api
    volumes:
       - sqllite-data:/app/data
  
  mongo:
    restart: always
    image: mongo
    volumes:
       - mongodb-data:/data

volumes:
  sqllite-data:
  mongodb-data: