version: '3.4'

services:
  recipieces-web:
    image: recipieces-web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - recipe-api

  recipe-api:
    image: recipe-api
    build:
      context: .
      dockerfile: RecipeApi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    ports:
      - "27017:27017"