#docker-compose.override.yml (Extended config for DEVELOPMENT env.)
version: '3.4'
services:
  recipe-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5000:80"

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "3000:80"
  
  mongo:
    ports:
      - "27017:27017"